### PR TITLE
Chris/update read me and fix parser.ts

### PR DESCRIPTION
**Pull request by ChristopherPark3**
fixes parser.ts and allows for extraction of multiple one way variables. Before we were just extracting the first variable that satisfied our condition.

### CODE REVIEW

**Review by kaseydn — APPROVED** [review]
Great job Chris!

**Review by hkulf41 — APPROVED** [review]
CLUTCH Chris

**Review by yosuketomita — APPROVED** [review]
Good job!

**Review by a-hend — APPROVED** [review]
Looks great Chris, good catch.  I noticed there is a console.log in the parser.ts file that needs removed.

**Pull request merged**
