### PR TITLE
Adds a browser version of VisiVue

### PR DESCRIPTION
**Pull request by a-hend**
Adds a new directory 'visivue-browser' to the 'src' directory that is a clone of VisiVue for the browser.  This enables development of the VisiVue VS Code extension with immediate refresh (hot loading) and the ability to log messages and receive errors in the console, neither of which are available in the VS Code Development Host.

### CODE REVIEW

**Review by ChristopherPark3 — APPROVED** [review]
Great work!

**Review by hkulf41 — APPROVED** [review]
Holy moly a browser version of the app?? Are you kidding me?? LGT!!!!

**Review by yosuketomita — APPROVED** [review]
A lot of work great job!

**Comment by kaseydn** [comment]
Awesome work!!!

**Pull request merged**
