### PR TITLE
Chris/parser.ts

### PR DESCRIPTION
**Pull request by ChristopherPark3**
Creates a base, functional parser. Still needs work in regards to pulling oneway data bound variables.

### CODE REVIEW

**Review by yosuketomita — APPROVED** [review]
Great parser job!

**Review by hkulf41 — APPROVED** [review]
Got the parsing down, spectacular!

**Comment by kaseydn** [comment]
Good stuff!!!

**Review by a-hend — APPROVED** [review]
nice work team!

**Pull request merged**
