### PR TITLE
Updates edges with color and animation

### PR DESCRIPTION
**Pull request by a-hend**
Updates Vue Flow edges with color change based on one-way, two-way data bound (or both) stateful variables, adds animation and increases width of edges for any type of stateful variable.

Removes outdated functionality from elements.js that was moved to App.vue.

Removes comments in App.vue.

### CODE REVIEW

**Review by ChristopherPark3 — APPROVED** [review]
nice abe!

**Review by yosuketomita — APPROVED** [review]
colored edges!

**Review by hkulf41 — APPROVED** [review]
Loving the implementation on creating colored, animated edges, LGTM!!!

**Comment by kaseydn** [comment]
Way to comb through those docs to get the styling to work. Loving the data flow visual!

**Pull request merged**
