### PR TITLE
Yosuke/front end

### PR DESCRIPTION
**Pull request by yosuketomita**

### CODE REVIEW

**Review by kaseydn — APPROVED** [review]
Nice job team. It's gonna look great all hooked up.

**Review by hkulf41 — APPROVED** [review]
Great work guys! Yeah!

**Review by a-hend — APPROVED** [review]
Nice work front-end team.  Looks like there will be some re-factoring in App and NodeTemplate before we merge to Main, but great job getting the node templates functional.

**Review by ChristopherPark3 — APPROVED** [review]
Great job!

**Pull request merged**
